language: python
python:
  - "2.6"
  - "2.7"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
before_script:
  - mysql -e 'create database sentry;'
  - psql -c 'create database sentry;' -U postgres
install:
  - pip install mysql-python
  - pip install psycopg2
  - make develop
script:
  - make test
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change