sudo: false
language: python
services:
  - memcached
  - riak
  - mysql
  - postgresql
  - redis-server
  - cassandra
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - "$HOME/virtualenv/python2.7.9"
env:
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgres
  global:
    - SENTRY_LIGHT_BUILD=1
    - SKIP_BACKEND_VALIDATION=1
install:
  - python -m pip install --upgrade pip==7.1.2
  - time make develop dev-postgres dev-mysql
before_script:
  - mysql -e 'create database sentry;'
  - psql -c 'create database sentry;' -U postgres
  - "echo \"create keyspace sentry with replication = {'class' : 'SimpleStrategy', 'replication_factor': 1};\" | cqlsh --cqlversion=3.0.3"
  - echo 'create table nodestore (key text primary key, value blob, flags int);' | cqlsh -k sentry --cqlversion=3.0.3
script:
  - make lint
  - make test-js
  - coverage run --source=src/sentry -m py.test tests
  - make test-cli
after_success:
  - codecov -e DB
